docker_registry_security_group:
  name: "docker_registry_sg_{{ env_nick[environ] }}"
  desc: the security group for the docker-registry vpc
  rules:
    - proto: tcp
      from_port: 5443
      to_port: 5443
      cidr_ip: "{{ gaia_cidr_block[environ] }}"
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ vpc_cidr_block }}"

# size in GB
docker_registry_volume_size: 60

# ssh keypair
docker_registry_keypair_name: "docker-registry-keypair-{{ env_nick[environ] }}"
docker_registry_keypair_file: "docker-registry-key-{{ env_nick[environ] }}.pem"

# https server certificate
gaia_ca_file: "ca.{{ vpc_dns_zone }}"
gaia_ca_subj: "/C=/ST=/L=/O=/CN={{ vpc_dns_zone }}"
docker_registry_cert_file: "docker-registry.{{ vpc_dns_zone }}"
docker_registry_cert_subj: "/C=/ST=/L=/O=/CN=docker-registry.{{ vpc_dns_zone }}"

docker_registry_lc_name: "registry-lc-{{ env_nick[environ] }}"
docker_registry_asg_name: "registry-asg-{{ env_nick[environ] }}"
docker_registry_health_check_period: 60
docker_registry_cluster_size: 2
docker_registry_min_cluster_size: 2
docker_registry_max_cluster_size: 2

docker_registry_instance_type: "{{ instance_type.docker_registry[environ] }}"
docker_registry_instance_tags: [ "Name": "docker-registry", "env": "{{ environ}}", "group": "gaia", "type": "docker-registry-vm", "decription": "Docker Registry Node" ]
