environ: "{{ lookup('env', 'GAIA_ENV') | default('production', true) }}"

env_nick:
  production: prod
  develop: dev


# CIDR Address Blocks
cidr_block:
  production: 10.0.0.0/16
  develop: 10.100.0.0/16

subnet_cidr:
  public:
    first:
      production: 10.0.1.0/24
      develop: 10.100.1.0/24
    second:
      production: 10.0.2.0/24
      develop: 10.100.2.0/24
  private:
    first:
      production: 10.0.3.0/24
      develop: 10.100.3.0/24
    second:
      production: 10.0.4.0/24
      develop: 10.100.4.0/24


# AWS EC2 Instance Type
instance_type:
  nat:
    production: t2.micro
    develop: t2.micro
  docker_registry:
    production: m3.large     # 2 vCPU, 7.5GB RAM, 1x32 SSD - $0.133 per Hour
    develop: t2.small        # 1CPU, 2GB, EBS storage - $0.026 per Hour
  bastion:
    production: t2.small     # 1 CPU, 2GB RAM, EBS storage - $0.026 per Hour
    develop: t2.micro
